### ISSUE TITLE
Process 'command '/Users/kazuakiurayama/.sdkman/candidates/java/11.0.18-amzn/bin/java'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/inspectus4playwright-java-sample-project#1]
In IntelliJ IDEA, I tried to run `AppWebKit` class. I got the following error

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/c55d67bf-2fa6-4c13-881f-c039129a8f26">

```
Execution failed for task ':app:com.kazurayam.inspectus.playwright.AppWebKit.main()'.
> Process 'command '/Users/kazuakiurayama/.sdkman/candidates/java/11.0.18-amzn/bin/java'' finished with non-zero exit value 1
```

**Comment by kazurayam** [comment]
I found the following post, that suggested a solution to the above case

https://stackoverflow.com/questions/49323867/gradle-bootrun-error-process-command-finished-with-non-zero-exit-value-1

**Comment by kazurayam** [comment]
In the Tool bar, IntelliJ IDEA > Settings... > Build, Execution, Deployment > Build Tools> Maven

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/d0f31248-0f50-4b28-8d75-d45fe6b7ae5b">

Gradle Project > Build and Run using: Gradle => IntelliJ

**Comment by kazurayam** [comment]
Then, a new error message came out:

```
/Users/kazuakiurayama/.sdkman/candidates/java/17.0.11-tem/bin/java -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=60086:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/kazuakiurayama/github/inspectus4playwright-java-sample-project/app/out/production/classes:/Users/kazuakiurayama/github/inspectus4playwright-java-sample-project/app/out/production/resources:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.5.6/afc75d260d838a3bddfb8f207c2805ed7d1b34f9/logback-classic-1.5.6.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/2.0.13/80229737f704b121a318bba5d5deacbcf395bc77/slf4j-api-2.0.13.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/com.microsoft.playwright/playwright/1.46.0/b7c2540f42bb0adf454fb3f736e6f705a8798d8a/playwright-1.46.0.jar:/Users/kazuakiurayama/.m2/repository/com/kazurayam/unittest-helper/0.5.2-SNAPSHOT/unittest-helper-0.5.2-SNAPSHOT.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.5.6/41cbe874701200c5624c19e0ab50d1b88dfcc77d/logback-core-1.5.6.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.11.0/527175ca6d81050b53bdd4c457a6d6e017626b0e/gson-2.11.0.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.3.0/152ea56b3a72f655d4fd677fc0ef2596c3dd5e6e/opentest4j-1.3.0.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/com.microsoft.playwright/driver-bundle/1.46.0/475b774e03c1ca6f37478d4421bfcaeb5f98a400/driver-bundle-1.46.0.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/com.microsoft.playwright/driver/1.46.0/3cc0f09883183e79f82ce3bdc6eb926845e4ae65/driver-1.46.0.jar:/Users/kazuakiurayama/github/dotfiles/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.27.0/91b2c29d8a6148b5e2e4930f070d4840e2e48e34/error_prone_annotations-2.27.0.jar com.kazurayam.inspectus.playwright.AppWebKit
06:06:30,648 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.5.6
06:06:30,652 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - No custom configurators were discovered as a service.
06:06:30,652 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
06:06:30,656 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
06:06:30,742 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
06:06:30,743 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
06:06:30,807 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 88 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
06:06:30,807 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
06:06:30,808 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
06:06:30,809 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
06:06:30,824 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/kazuakiurayama/github/inspectus4playwright-java-sample-project/app/out/production/resources/logback.xml]
06:06:31,017 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - <level> element is deprecated. Near [level] on line 9
06:06:31,017 |-WARN in ch.qos.logback.classic.joran.action.LevelAction - Please use "level" attribute within <logger> or <root> elements instead.
06:06:31,168 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
06:06:31,168 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
06:06:31,182 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
06:06:31,236 |-INFO in ch.qos.logback.classic.model.processor.LevelModelHandler - com.kazurayam.unittest level set to DEBUG
06:06:31,237 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[com.kazurayam.unittest]
06:06:31,238 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
06:06:31,238 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
06:06:31,238 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@3bb9a3ff - End of configuration.
06:06:31,244 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@661972b0 - Registering current configuration as safe fallback point
06:06:31,244 |-INFO in ch.qos.logback.classic.util.ContextInitializer@7c729a55 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 436 milliseconds. ExecutionStatus=DO_NOT_INVOKE_NEXT_IF_ANY

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.IllegalStateException: [resolveProjectDirectoryViaClasspath] unable to resolve the project directory via classpath
	at com.kazurayam.unittest.ProjectDirectoryResolver.resolveProjectDirectoryViaClasspath(ProjectDirectoryResolver.java:172)
	at com.kazurayam.unittest.TestOutputOrganizer$Builder.build(TestOutputOrganizer.java:358)
	at com.kazurayam.inspectus.playwright.AppWebKit.<clinit>(AppWebKit.java:17)

Process finished with exit code 1

```

**Comment by kazurayam** [comment]
OK.
I was aware that I have another problem in the unittest-helper library.

So, I will close this issue.

**Comment by kazurayam** [comment]
I tried this:

```
~/github/inspectus4playwright-java-sample-project git:[master]
gradle app:clean app:run

BUILD SUCCESSFUL in 8s
```

This implies that if I let Gradle to to run the main() of the AppWebKit class, then no "Process 'command '/Users/kazuakiurayama/.sdkman/candidates/java/11.0.18-amzn/bin/java'' finished with non-zero exit value 1 " message was emitted.

**Comment by kazurayam** [comment]
A fact is that I right-clicked the `main()` method of AppWebKit class in the editor in IntelliJ IDEA to let "run the AppWebKit". When I did it with `Gradle` chosen as "run by".

This configuration might confused the system.
